language: python
cache: pip
install:
  - pip install pytest
  - pip install .

script:
  # we need to separate these 2 tests because of issue #76
  - pytest -s --ignore=fastmri_recon/tests/training_scripts fastmri_recon/tests
  - pytest -s fastmri_recon/tests/training_scripts
